import { Item } from "./types";

// Starter items are taken/adapted from:
// - UIUC Physics 101 Formula Sheet (2025)
// - FYKOS "List of constants" (2024)
//
// These are practical PHYS 1–2 level entries. Add more any time via the UI.

const base: Item[] = [
  // --- Kinematics
  {
    id: "kinematics-1",
    kind: "equation",
    name: "Definition of acceleration",
    latex: "a = \\frac{\\Delta v}{\\Delta t}",
    text: "Average acceleration",
    tags: ["kinematics", "acceleration"],
    category: "Kinematics",
    popularity: 8,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "kinematics-2",
    kind: "equation",
    name: "Uniform acceleration (1)",
    latex: "v = v_0 + a t",
    text: "Velocity update under constant acceleration",
    tags: ["kinematics", "projectile"],
    category: "Kinematics",
    popularity: 10,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "kinematics-3",
    kind: "equation",
    name: "Uniform acceleration (2)",
    latex: "x = x_0 + v_0 t + \\tfrac{1}{2} a t^2",
    text: "Displacement under constant acceleration",
    tags: ["kinematics"],
    category: "Kinematics",
    popularity: 9,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "kinematics-4",
    kind: "equation",
    name: "Uniform acceleration (3)",
    latex: "v^2 = v_0^2 + 2 a \\Delta x",
    text: "Velocity-position relation without time",
    tags: ["kinematics"],
    category: "Kinematics",
    popularity: 9,
    source: "UIUC PHYS 101 formula sheet",
  },
  // --- Dynamics / Energy
  {
    id: "newton-2",
    kind: "equation",
    name: "Newton's 2nd Law",
    latex: "\\sum F = m a",
    text: "Net force equals mass times acceleration",
    tags: ["dynamics", "forces"],
    category: "Dynamics",
    popularity: 10,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "work-energy",
    kind: "equation",
    name: "Work–Kinetic Energy",
    latex: "W = \\Delta K",
    text: "Net work equals change in kinetic energy",
    tags: ["work", "energy"],
    category: "Work & Energy",
    popularity: 8,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "grav-ue",
    kind: "equation",
    name: "Gravitational potential (near Earth)",
    latex: "U = m g h",
    text: "Approximation near Earth's surface",
    tags: ["energy", "gravity"],
    category: "Work & Energy",
    popularity: 7,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "spring-energy",
    kind: "equation",
    name: "Spring potential energy",
    latex: "U_s = \\tfrac{1}{2} k x^2",
    text: "Hooke's law energy",
    tags: ["spring", "energy"],
    category: "Work & Energy",
    popularity: 7,
    source: "UIUC PHYS 101 formula sheet",
  },
  // --- Momentum
  {
    id: "momentum",
    kind: "equation",
    name: "Momentum",
    latex: "p = m v",
    text: "Linear momentum",
    tags: ["momentum"],
    category: "Momentum",
    popularity: 8,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "impulse",
    kind: "equation",
    name: "Impulse–Momentum",
    latex: "J = F \\Delta t = \\Delta p",
    text: "Impulse equals change in momentum",
    tags: ["impulse", "momentum"],
    category: "Momentum",
    popularity: 7,
    source: "UIUC PHYS 101 formula sheet",
  },
  // --- Rotation
  {
    id: "rot-kin-1",
    kind: "equation",
    name: "Angular kinematics (1)",
    latex: "\\omega = \\omega_0 + \\alpha t",
    text: "Constant angular acceleration",
    tags: ["rotation"],
    category: "Rotation",
    popularity: 6,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "rot-energy",
    kind: "equation",
    name: "Rotational kinetic energy",
    latex: "K = \\tfrac{1}{2} I \\omega^2",
    text: "Rotational energy",
    tags: ["rotation", "energy"],
    category: "Rotation",
    popularity: 6,
    source: "UIUC PHYS 101 formula sheet",
  },
  // --- Fluids / Thermo / SHM
  {
    id: "ideal-gas",
    kind: "equation",
    name: "Ideal gas law",
    latex: "P V = n R T",
    text: "Moles form",
    tags: ["thermo", "gas"],
    category: "Thermodynamics",
    popularity: 9,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "simple-spring",
    kind: "equation",
    name: "SHM: mass–spring angular frequency",
    latex: "\\omega = \\sqrt{\\frac{k}{m}}",
    text: "Simple harmonic motion",
    tags: ["shm", "spring"],
    category: "Oscillations",
    popularity: 7,
    source: "UIUC PHYS 101 formula sheet",
  },
  // --- Constants (FYKOS or common values)
  {
    id: "c",
    kind: "constant",
    name: "Speed of light in vacuum",
    symbol: "c",
    value: "2.998e8",
    units: "m s^-1",
    latex: "c = 2.998 \\times 10^{8} \\, \\text{m}\\,\\text{s}^{-1}",
    text: "Exact by definition",
    tags: ["em", "fundamental"],
    category: "Constants",
    popularity: 10,
    source: "FYKOS constants",
  },
  {
    id: "g",
    kind: "constant",
    name: "Standard gravity (approx.)",
    symbol: "g",
    value: "9.81",
    units: "m s^-2",
    latex: "g \\approx 9.81 \\, \\text{m}\\,\\text{s}^{-2}",
    text: "Near Earth's surface, typical",
    tags: ["gravity"],
    category: "Constants",
    popularity: 10,
    source: "FYKOS constants",
  },
  {
    id: "G",
    kind: "constant",
    name: "Gravitational constant",
    symbol: "G",
    value: "6.674e-11",
    units: "m^3 kg^-1 s^-2",
    latex: "G = 6.674 \\times 10^{-11} \\, \\text{m}^3\\,\\text{kg}^{-1}\\,\\text{s}^{-2}",
    text: "Universal gravitational constant",
    tags: ["gravity"],
    category: "Constants",
    popularity: 8,
    source: "FYKOS constants",
  },
  {
    id: "NA",
    kind: "constant",
    name: "Avogadro constant",
    symbol: "N_A",
    value: "6.022e23",
    units: "mol^-1",
    latex: "N_A = 6.022 \\times 10^{23} \\, \\text{mol}^{-1}",
    text: "Particles per mole (exact by definition in SI)",
    tags: ["thermo"],
    category: "Constants",
    popularity: 8,
    source: "FYKOS constants",
  },
  {
    id: "kB",
    kind: "constant",
    name: "Boltzmann constant",
    symbol: "k_B",
    value: "1.381e-23",
    units: "J K^-1",
    latex: "k_B = 1.381 \\times 10^{-23} \\, \\text{J}\\,\\text{K}^{-1}",
    text: "Relates temperature to energy",
    tags: ["thermo"],
    category: "Constants",
    popularity: 7,
    source: "FYKOS constants",
  },
  {
    id: "R",
    kind: "constant",
    name: "Molar gas constant",
    symbol: "R",
    value: "8.314",
    units: "J mol^-1 K^-1",
    latex: "R = 8.314 \\, \\text{J}\\,\\text{mol}^{-1}\\,\\text{K}^{-1}",
    text: "Ideal gas constant",
    tags: ["thermo"],
    category: "Constants",
    popularity: 7,
    source: "FYKOS constants",
  },
];

const ap2Extras: Item[] = [
  /* ---------------- Electricity & Magnetism ---------------- */
  {
    id: "em-coulomb-law",
    kind: "equation",
    name: "Coulomb’s law",
    latex: "F = k\\,\\dfrac{q_1 q_2}{r^2} = \\dfrac{1}{4\\pi\\varepsilon_0}\\,\\dfrac{q_1 q_2}{r^2}",
    text: "Force between two point charges (magnitude).",
    tags: ["electric", "force", "point charge"],
    category: "Electricity & Magnetism",
    popularity: 8,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "em-field-from-charge",
    kind: "equation",
    name: "Electric field of a point charge",
    latex: "E = k\\,\\dfrac{q}{r^2} = \\dfrac{1}{4\\pi\\varepsilon_0}\\,\\dfrac{q}{r^2}",
    text: "Magnitude of E due to a single point charge.",
    tags: ["electric field", "point charge"],
    category: "Electricity & Magnetism",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "em-field-def",
    kind: "equation",
    name: "Electric field definition",
    latex: "E = \\dfrac{F}{q}",
    text: "Force per unit charge.",
    tags: ["electric field", "definition"],
    category: "Electricity & Magnetism",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "em-U-electric",
    kind: "equation",
    name: "Electric potential energy (2 charges)",
    latex: "U = k\\,\\dfrac{q_1 q_2}{r}",
    text: "Potential energy of two point charges.",
    tags: ["potential energy", "electric"],
    category: "Electricity & Magnetism",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "em-V-point",
    kind: "equation",
    name: "Electric potential of a point charge",
    latex: "V = k\\,\\dfrac{q}{r}",
    text: "Potential due to a single point charge.",
    tags: ["potential", "electric"],
    category: "Electricity & Magnetism",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "em-V-Uq",
    kind: "equation",
    name: "Potential–energy relation",
    latex: "V = \\dfrac{U}{q}",
    text: "Potential equals potential energy per unit charge.",
    tags: ["potential", "energy"],
    category: "Electricity & Magnetism",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "em-E-gradV-1D",
    kind: "equation",
    name: "Field–potential (1D magnitude)",
    latex: "E = \\dfrac{\\Delta V}{\\Delta r}",
    text: "Magnitude relation in 1D (sheet lists the unsigned form).",
    tags: ["electric field", "potential"],
    category: "Electricity & Magnetism",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },

  {
    /* Capacitance & circuits */ id: "cap-def",
    kind: "equation",
    name: "Capacitance definition",
    latex: "C = \\dfrac{Q}{V}",
    text: "Charge stored per volt.",
    tags: ["capacitance"],
    category: "Electricity & Magnetism",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "cap-parallel-plate",
    kind: "equation",
    name: "Parallel-plate capacitance",
    latex: "C = \\kappa\\,\\varepsilon_0\\,\\dfrac{A}{d}",
    text: "With dielectric constant \\(\\kappa\\).",
    tags: ["capacitor", "parallel plate"],
    category: "Electricity & Magnetism",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "cap-plate-field",
    kind: "equation",
    name: "Field between plates (vacuum)",
    latex: "E = \\dfrac{Q}{\\varepsilon_0 A}",
    text: "Uniform field magnitude between large plates.",
    tags: ["electric field", "capacitor"],
    category: "Electricity & Magnetism",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "cap-energy",
    kind: "equation",
    name: "Energy stored in a capacitor",
    latex: "U = \\tfrac{1}{2} QV = \\tfrac{1}{2}CV^2",
    text: "Electrostatic energy in a capacitor.",
    tags: ["energy", "capacitor"],
    category: "Electricity & Magnetism",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },

  {
    /* DC circuit basics */ id: "c-current-def",
    kind: "equation",
    name: "Current definition",
    latex: "I = \\dfrac{\\Delta Q}{\\Delta t}",
    text: "Rate of charge flow.",
    tags: ["current"],
    category: "Electricity & Magnetism",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "c-resistivity",
    kind: "equation",
    name: "Resistance from resistivity",
    latex: "R = \\rho\\,\\dfrac{\\ell}{A}",
    text: "Uniform wire of length \\(\\ell\\) and cross-section \\(A\\).",
    tags: ["resistance", "resistivity"],
    category: "Electricity & Magnetism",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "c-power",
    kind: "equation",
    name: "Electrical power",
    latex: "P = IV = I^2 R = \\dfrac{V^2}{R}",
    text: "Equivalent power forms.",
    tags: ["power", "circuits"],
    category: "Electricity & Magnetism",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "c-req-series",
    kind: "equation",
    name: "Series resistors",
    latex: "R_{\\mathrm{eq}} = \\sum_i R_i",
    text: "Equivalent resistance in series.",
    tags: ["resistors", "series"],
    category: "Electricity & Magnetism",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "c-req-parallel",
    kind: "equation",
    name: "Parallel resistors",
    latex: "\\dfrac{1}{R_{\\mathrm{eq}}} = \\sum_i \\dfrac{1}{R_i}",
    text: "Equivalent resistance in parallel.",
    tags: ["resistors", "parallel"],
    category: "Electricity & Magnetism",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "c-ceq-parallel",
    kind: "equation",
    name: "Parallel capacitors",
    latex: "C_{\\mathrm{eq}} = \\sum_i C_i",
    text: "Capacitances add in parallel.",
    tags: ["capacitors", "parallel"],
    category: "Electricity & Magnetism",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "c-ceq-series",
    kind: "equation",
    name: "Series capacitors",
    latex: "\\dfrac{1}{C_{\\mathrm{eq}}} = \\sum_i \\dfrac{1}{C_i}",
    text: "Inverse-add in series.",
    tags: ["capacitors", "series"],
    category: "Electricity & Magnetism",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "c-rc-tau",
    kind: "equation",
    name: "RC time constant",
    latex: "\\tau = RC",
    text: "Natural time scale of an RC circuit.",
    tags: ["RC", "time constant"],
    category: "Electricity & Magnetism",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },

  {
    /* Magnetism & induction */ id: "B-force-charge",
    kind: "equation",
    name: "Magnetic force on a moving charge",
    latex: "F = q\\,vB\\,\\sin\\theta",
    text: "Magnitude of force on charge q moving at v in field B.",
    tags: ["magnetic", "Lorentz force"],
    category: "Electricity & Magnetism",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "B-force-wire",
    kind: "equation",
    name: "Magnetic force on a wire",
    latex: "F = I\\,\\ell\\,B\\,\\sin\\theta",
    text: "Straight segment length \\(\\ell\\).",
    tags: ["magnetic", "current"],
    category: "Electricity & Magnetism",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "B-long-wire",
    kind: "equation",
    name: "Field of a long straight wire",
    latex: "B = \\dfrac{\\mu_0 I}{2\\pi r}",
    text: "Magnitude at distance r.",
    tags: ["magnetic field", "wire"],
    category: "Electricity & Magnetism",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "flux-def",
    kind: "equation",
    name: "Magnetic flux",
    latex: "\\Phi_B = \\vec B\\cdot\\vec A = BA\\cos\\theta",
    text: "Flux through area A.",
    tags: ["flux"],
    category: "Electricity & Magnetism",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "faraday-mag",
    kind: "equation",
    name: "Faraday’s law (magnitude)",
    latex: "\\mathcal{E} = \\dfrac{\\Delta \\Phi_B}{\\Delta t}",
    text: "Emf from changing magnetic flux (sheet lists magnitude).",
    tags: ["induction", "emf"],
    category: "Electricity & Magnetism",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "emf-motional",
    kind: "equation",
    name: "Motional emf",
    latex: "\\mathcal{E} = B\\,\\ell\\,v",
    text: "Conductor length \\(\\ell\\) moving at \\(v\\) across B.",
    tags: ["emf", "motion"],
    category: "Electricity & Magnetism",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },

  /* ---------------- Thermodynamics & Fluids ---------------- */
  {
    id: "pressure-def",
    kind: "equation",
    name: "Pressure definition",
    latex: "P = \\dfrac{F_{\\perp}}{A}",
    text: "Normal force per area.",
    tags: ["pressure"],
    category: "Thermodynamics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "kt-avg-ke",
    kind: "equation",
    name: "Average translational KE",
    latex: "K_{\\mathrm{avg}} = \\tfrac{3}{2} k_B T",
    text: "Monatomic ideal gas.",
    tags: ["kinetic theory"],
    category: "Thermodynamics",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "kt-vrms",
    kind: "equation",
    name: "Root-mean-square speed",
    latex: "v_{\\mathrm{rms}} = \\sqrt{\\dfrac{3 k_B T}{m}}",
    text: "Ideal gas molecules.",
    tags: ["kinetic theory"],
    category: "Thermodynamics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "heat-conduction",
    kind: "equation",
    name: "Thermal conduction rate",
    latex: "\\dfrac{Q}{t} = kA\\,\\dfrac{\\Delta T}{L}",
    text: "Steady 1D conduction.",
    tags: ["heat", "conduction"],
    category: "Thermodynamics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  // (Ideal gas law already in your seed as id="ideal-gas")
  {
    id: "U-mono",
    kind: "equation",
    name: "Internal energy (monatomic ideal gas)",
    latex: "U = \\tfrac{3}{2} nRT = \\tfrac{3}{2} N k_B T",
    text: "Translational modes only.",
    tags: ["internal energy"],
    category: "Thermodynamics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "work-constP",
    kind: "equation",
    name: "Work at constant pressure",
    latex: "W = -P\\,\\Delta V",
    text: "Sign convention as on sheet (work on the gas positive).",
    tags: ["work", "thermo"],
    category: "Thermodynamics",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "first-law",
    kind: "equation",
    name: "First law (sheet sign convention)",
    latex: "\\Delta U = Q + W",
    text: "Change in internal energy.",
    tags: ["first law"],
    category: "Thermodynamics",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "heat-temp",
    kind: "equation",
    name: "Sensible heating",
    latex: "Q = mc\\,\\Delta T",
    text: "Heat to change temperature.",
    tags: ["heat"],
    category: "Thermodynamics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },

  // Fluids
  {
    id: "hydrostatic",
    kind: "equation",
    name: "Hydrostatic pressure",
    latex: "P = P_0 + \\rho g h",
    text: "Pressure at depth h.",
    tags: ["fluids", "pressure"],
    category: "Fluids",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "gauge-pressure",
    kind: "equation",
    name: "Gauge pressure",
    latex: "P_{\\text{gauge}} = \\rho g h",
    text: "Pressure above atmospheric.",
    tags: ["fluids"],
    category: "Fluids",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "continuity",
    kind: "equation",
    name: "Continuity (incompressible)",
    latex: "A v = \\text{constant}",
    text: "Steady flow.",
    tags: ["fluids", "continuity"],
    category: "Fluids",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "bernoulli",
    kind: "equation",
    name: "Bernoulli (two points)",
    latex: "P_1 + \\rho g y_1 + \\tfrac{1}{2}\\rho v_1^2 = P_2 + \\rho g y_2 + \\tfrac{1}{2}\\rho v_2^2",
    text: "Ideal fluid along a streamline.",
    tags: ["fluids", "energy"],
    category: "Fluids",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "buoyancy",
    kind: "equation",
    name: "Buoyant force",
    latex: "F_b = \\rho V g",
    text: "Weight of displaced fluid.",
    tags: ["fluids", "buoyancy"],
    category: "Fluids",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },

  /* ---------------- Waves, Sound & Optics ---------------- */
  {
    id: "wave-v",
    kind: "equation",
    name: "Wave speed",
    latex: "v = f\\,\\lambda",
    text: "All waves.",
    tags: ["waves"],
    category: "Waves & Optics",
    popularity: 8,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "index-speed",
    kind: "equation",
    name: "Index and speed",
    latex: "n = \\dfrac{c}{v}",
    text: "Speed of light in a medium.",
    tags: ["optics", "index"],
    category: "Waves & Optics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "snell",
    kind: "equation",
    name: "Snell’s law",
    latex: "n_i\\sin\\theta_i = n_t\\sin\\theta_t",
    text: "Refraction at a boundary.",
    tags: ["optics", "refraction"],
    category: "Waves & Optics",
    popularity: 8,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "thin-lens",
    kind: "equation",
    name: "Thin lens / mirror equation",
    latex: "\\dfrac{1}{f} = \\dfrac{1}{s_o} + \\dfrac{1}{s_i}",
    text: "Paraxial approximation.",
    tags: ["optics", "imaging"],
    category: "Waves & Optics",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "magnification",
    kind: "equation",
    name: "Magnification",
    latex: "M = \\dfrac{h_i}{h_o} = -\\dfrac{s_i}{s_o}",
    text: "Sign convention as usual.",
    tags: ["optics", "imaging"],
    category: "Waves & Optics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "double-slit",
    kind: "equation",
    name: "Double-slit maxima",
    latex: "d\\sin\\theta = m\\,\\lambda",
    text: "m = 0,\\,\\pm1,\\,\\pm2,\\dots",
    tags: ["interference"],
    category: "Waves & Optics",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "single-slit-min",
    kind: "equation",
    name: "Single-slit minima",
    latex: "a\\sin\\theta = m\\,\\lambda",
    text: "m = 1,2,3,\\dots",
    tags: ["diffraction"],
    category: "Waves & Optics",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "small-angle-fringes",
    kind: "equation",
    name: "Fringe position (small-angle approx.)",
    latex: "y_m \\approx m\\,\\dfrac{\\lambda L}{d}",
    text: "Screen distance L, slit spacing d.",
    tags: ["interference"],
    category: "Waves & Optics",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "small-angle-single",
    kind: "equation",
    name: "Single-slit minima (small-angle)",
    latex: "y_m \\approx m\\,\\dfrac{\\lambda L}{a}",
    text: "Screen distance L, slit width a.",
    tags: ["diffraction"],
    category: "Waves & Optics",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "string-harmonics",
    kind: "equation",
    name: "String harmonics",
    latex: "f_n = n\\,\\dfrac{v}{2L}\\quad(n=1,2,3,\\dots)",
    text: "Standing waves on a string with fixed ends.",
    tags: ["standing waves"],
    category: "Waves & Optics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "beat-frequency",
    kind: "equation",
    name: "Beat frequency",
    latex: "f_{\\text{beat}} = |f_1 - f_2|",
    text: "Interference of close frequencies.",
    tags: ["sound", "beats"],
    category: "Waves & Optics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "string-speed",
    kind: "equation",
    name: "Wave speed on a string",
    latex: "v = \\sqrt{\\dfrac{F_T}{\\mu}}",
    text: "Tension \\(F_T\\), linear density \\(\\mu\\).",
    tags: ["waves", "string"],
    category: "Waves & Optics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "period-omega",
    kind: "equation",
    name: "Period and angular frequency",
    latex: "T = \\dfrac{1}{f},\\quad \\omega = 2\\pi f",
    text: "Basic relations.",
    tags: ["period", "frequency"],
    category: "Waves & Optics",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },

  /* ---------------- Modern Physics ---------------- */
  {
    id: "photon-energy",
    kind: "equation",
    name: "Photon energy",
    latex: "E = h f",
    text: "Energy of a single photon.",
    tags: ["quantum", "photon"],
    category: "Modern Physics",
    popularity: 8,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "photon-momentum",
    kind: "equation",
    name: "Photon momentum",
    latex: "p = \\dfrac{h}{\\lambda}",
    text: "De Broglie/photons.",
    tags: ["quantum", "momentum"],
    category: "Modern Physics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "photoelectric",
    kind: "equation",
    name: "Photoelectric effect",
    latex: "K_{\\max} = h f - \\phi",
    text: "Stopping potential relates to \\(K_{\\max}\\).",
    tags: ["photoelectric"],
    category: "Modern Physics",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "mass-energy",
    kind: "equation",
    name: "Mass–energy equivalence",
    latex: "E = mc^2",
    text: "Rest energy.",
    tags: ["relativity"],
    category: "Modern Physics",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "de-broglie",
    kind: "equation",
    name: "De Broglie wavelength",
    latex: "\\lambda = \\dfrac{h}{p}",
    text: "Matter waves.",
    tags: ["quantum"],
    category: "Modern Physics",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "radioactive-decay",
    kind: "equation",
    name: "Radioactive decay law",
    latex: "N(t) = N_0 e^{-\\lambda t}",
    text: "Exponential decay.",
    tags: ["nuclear", "decay"],
    category: "Modern Physics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "half-life",
    kind: "equation",
    name: "Half-life",
    latex: "t_{1/2} = \\dfrac{\\ln 2}{\\lambda}",
    text: "Time for \\(N\\) to halve.",
    tags: ["nuclear", "decay"],
    category: "Modern Physics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "stefan-boltzmann",
    kind: "equation",
    name: "Stefan–Boltzmann law",
    latex: "\\dfrac{P}{A} = \\sigma T^4",
    text: "Blackbody power per area.",
    tags: ["thermal radiation"],
    category: "Modern Physics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "wien",
    kind: "equation",
    name: "Wien’s displacement",
    latex: "\\lambda_{\\max} T = b",
    text: "Peak wavelength–temperature product.",
    tags: ["thermal radiation"],
    category: "Modern Physics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },

  /* ---------------- Mechanics (extra) ---------------- */
  {
    id: "centripetal-accel",
    kind: "equation",
    name: "Centripetal acceleration",
    latex: "a_c = \\dfrac{v^2}{r}",
    text: "Uniform circular motion.",
    tags: ["circular motion"],
    category: "Dynamics",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "work-def",
    kind: "equation",
    name: "Work (constant force)",
    latex: "W = F d\\cos\\theta",
    text: "Mechanical work by a constant force.",
    tags: ["work", "energy"],
    category: "Work & Energy",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "friction-static",
    kind: "equation",
    name: "Static friction (limit)",
    latex: "f_s \\le \\mu_s\\,F_n",
    text: "Maximum static friction magnitude.",
    tags: ["friction"],
    category: "Dynamics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "newton-universal",
    kind: "equation",
    name: "Newton’s law of gravitation",
    latex: "F_g = G\\,\\dfrac{m_1 m_2}{r^2}",
    text: "Magnitude of gravitational force.",
    tags: ["gravity", "force"],
    category: "Dynamics",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "U-grav-universal",
    kind: "equation",
    name: "Gravitational potential energy (two masses)",
    latex: "U = -\\,G\\,\\dfrac{m_1 m_2}{r}",
    text: "Standard sign convention (negative).",
    tags: ["gravity", "potential energy"],
    category: "Work & Energy",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "power-mech",
    kind: "equation",
    name: "Mechanical power",
    latex: "P = \\dfrac{W}{t} = Fv",
    text: "Rate of doing work; dot product implied.",
    tags: ["power"],
    category: "Work & Energy",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },

  // Rotation add-ons
  {
    id: "torque-basic",
    kind: "equation",
    name: "Torque (lever arm)",
    latex: "\\tau = r F_{\\perp}",
    text: "Moment of a force about a pivot.",
    tags: ["torque"],
    category: "Rotation",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "rot-newton",
    kind: "equation",
    name: "Rotational dynamics",
    latex: "\\tau_{\\text{net}} = I\\,\\alpha",
    text: "Angular analog of F = ma.",
    tags: ["rotation", "dynamics"],
    category: "Rotation",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "ang-momentum",
    kind: "equation",
    name: "Angular momentum (rigid body)",
    latex: "L = I\\,\\omega",
    text: "Rigid body about fixed axis.",
    tags: ["angular momentum"],
    category: "Rotation",
    popularity: 6,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "rot-work",
    kind: "equation",
    name: "Rotational work",
    latex: "W = \\tau\\,\\Delta\\theta",
    text: "Work by a constant torque.",
    tags: ["rotation", "work"],
    category: "Rotation",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },

  // SHM add-ons
  {
    id: "shm-period",
    kind: "equation",
    name: "Mass–spring period (SHM)",
    latex: "T = 2\\pi\\,\\sqrt{\\dfrac{m}{k}}",
    text: "Small oscillations.",
    tags: ["shm", "period"],
    category: "Oscillations",
    popularity: 7,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
  {
    id: "shm-x-of-t",
    kind: "equation",
    name: "SHM displacement vs time",
    latex: "x(t) = A\\cos(2\\pi f t)",
    text: "One common phase convention.",
    tags: ["shm", "kinematics"],
    category: "Oscillations",
    popularity: 5,
    source: "AP Physics 2 Equation Sheet (College Board, 2024)",
  },
];

const ap2EarlierAdds: Item[] = [
  /* ------------ Center of mass ------------ */
  {
    id: "cm-1d",
    kind: "equation",
    name: "Center of mass (1D)",
    latex: "\\bar x_{\\mathrm{cm}} = \\dfrac{\\sum m_i x_i}{\\sum m_i}",
    text: "1D COM of discrete masses.",
    tags: ["center of mass"],
    category: "Momentum",
    popularity: 6,
    source: "Std. mechanics identity",
  },
  {
    id: "vcm-from-p",
    kind: "equation",
    name: "COM velocity from momentum",
    latex: "\\vec v_{\\mathrm{cm}} = \\dfrac{\\sum \\vec p_i}{\\sum m_i}",
    text: "Total momentum divided by total mass.",
    tags: ["center of mass", "momentum"],
    category: "Momentum",
    popularity: 6,
    source: "Std. mechanics identity",
  },

  /* ------------ Angular kinematics ------------ */
  {
    id: "rot-kin-2-eq",
    kind: "equation",
    name: "Angular kinematics (2)",
    latex: "\\theta = \\theta_0 + \\omega_0 t + \\tfrac{1}{2}\\alpha t^2",
    text: "Constant angular acceleration.",
    tags: ["rotation", "kinematics"],
    category: "Rotation",
    popularity: 6,
    source: "Std. rotational kinematics",
  },
  {
    id: "rot-kin-3-eq",
    kind: "equation",
    name: "Angular kinematics (3)",
    latex: "\\omega^2 = \\omega_0^2 + 2\\alpha(\\theta - \\theta_0)",
    text: "No explicit time.",
    tags: ["rotation", "kinematics"],
    category: "Rotation",
    popularity: 6,
    source: "Std. rotational kinematics",
  },

  /* ------------ Circular motion relations ------------ */
  {
    id: "tangential-accel",
    kind: "equation",
    name: "Tangential acceleration",
    latex: "a_t = r\\alpha",
    text: "Linear tangential acceleration.",
    tags: ["circular motion"],
    category: "Rotation",
    popularity: 6,
    source: "Std. circular motion",
  },
  {
    id: "arc-length",
    kind: "equation",
    name: "Arc length",
    latex: "s = r\\,\\Delta\\theta",
    text: "Small-angle/arc definition.",
    tags: ["circular motion", "geometry"],
    category: "Rotation",
    popularity: 5,
    source: "Std. circular motion",
  },
  {
    id: "linear-speed-angular",
    kind: "equation",
    name: "Linear speed from angular speed",
    latex: "v = r\\omega",
    text: "Uniform circular motion relation.",
    tags: ["circular motion"],
    category: "Rotation",
    popularity: 6,
    source: "Std. circular motion",
  },

  /* ------------ Rigid body theorems ------------ */
  {
    id: "parallel-axis",
    kind: "equation",
    name: "Parallel-axis theorem",
    latex: "I' = I_{\\mathrm{cm}} + M d^2",
    text: "Moment about axis parallel to COM axis offset by d.",
    tags: ["moment of inertia"],
    category: "Rotation",
    popularity: 7,
    source: "Std. rigid body theorem",
  },
  {
    id: "angular-impulse",
    kind: "equation",
    name: "Angular impulse",
    latex: "\\Delta L = \\tau\\,\\Delta t",
    text: "Change in angular momentum for constant torque.",
    tags: ["impulse", "torque"],
    category: "Rotation",
    popularity: 6,
    source: "Std. rotational dynamics",
  },

  /* ------------ Modern physics ------------ */
  {
    id: "compton-shift",
    kind: "equation",
    name: "Compton shift",
    latex: "\\Delta\\lambda = \\dfrac{h}{m_e c}\\,(1-\\cos\\theta)",
    text: "Photon scattering from an electron.",
    tags: ["modern", "quantum"],
    category: "Modern Physics",
    popularity: 6,
    source: "Compton scattering",
  },

  /* ------------ Useful constants (not yet in seed) ------------ */
  {
    id: "epsilon0",
    kind: "constant",
    name: "Vacuum permittivity",
    symbol: "ε0",
    value: "8.85e-12",
    units: "C^2 N^-1 m^-2",
    latex: "\\varepsilon_0 = 8.85\\times 10^{-12}\\,\\text{C}^2\\,\\text{N}^{-1}\\,\\text{m}^{-2}",
    text: "Electric constant (approx.).",
    tags: ["em", "constant"],
    category: "Constants",
    popularity: 7,
    source: "AP Physics 2 constants table",
  },
  {
    id: "mu0",
    kind: "constant",
    name: "Vacuum permeability",
    symbol: "μ0",
    value: "1.257e-6",
    units: "T m A^-1",
    latex: "\\mu_0 \\approx 4\\pi\\times10^{-7}\\,\\text{T}\\,\\text{m}\\,\\text{A}^{-1}",
    text: "Magnetic constant (approx.).",
    tags: ["em", "constant"],
    category: "Constants",
    popularity: 7,
    source: "AP Physics 2 constants table",
  },
  {
    id: "elementary-charge",
    kind: "constant",
    name: "Elementary charge",
    symbol: "e",
    value: "1.60e-19",
    units: "C",
    latex: "e = 1.60\\times10^{-19}\\,\\text{C}",
    text: "Magnitude of the electron charge.",
    tags: ["em", "constant"],
    category: "Constants",
    popularity: 8,
    source: "AP Physics 2 constants table",
  },
  {
    id: "planck-h",
    kind: "constant",
    name: "Planck constant",
    symbol: "h",
    value: "6.63e-34",
    units: "J s",
    latex: "h \\approx 6.63\\times10^{-34}\\,\\text{J}\\,\\text{s}",
    text: "Quantum of action.",
    tags: ["modern", "constant"],
    category: "Constants",
    popularity: 8,
    source: "AP Physics 2 constants table",
  },
  {
    id: "stefan-boltzmann-sigma",
    kind: "constant",
    name: "Stefan–Boltzmann constant",
    symbol: "σ",
    value: "5.67e-8",
    units: "W m^-2 K^-4",
    latex: "\\sigma = 5.67\\times10^{-8}\\,\\text{W}\\,\\text{m}^{-2}\\,\\text{K}^{-4}",
    text: "Blackbody radiation constant.",
    tags: ["modern", "thermal", "constant"],
    category: "Constants",
    popularity: 6,
    source: "AP Physics 2 constants table",
  },
  {
    id: "wien-b",
    kind: "constant",
    name: "Wien’s displacement constant",
    symbol: "b",
    value: "2.90e-3",
    units: "m K",
    latex: "b = 2.90\\times10^{-3}\\,\\text{m}\\,\\text{K}",
    text: "Peak wavelength–temperature product.",
    tags: ["modern", "thermal", "constant"],
    category: "Constants",
    popularity: 6,
    source: "AP Physics 2 constants table",
  },
  {
    id: "coulomb-k",
    kind: "constant",
    name: "Coulomb constant",
    symbol: "k_e",
    value: "8.99e9",
    units: "N m^2 C^-2",
    latex: "k_e \\approx 8.99\\times10^{9}\\,\\text{N}\\,\\text{m}^2\\,\\text{C}^{-2}",
    text: "1/(4π ε0).",
    tags: ["em", "constant"],
    category: "Constants",
    popularity: 6,
    source: "AP Physics 2 constants table",
  },
  {
    id: "electron-volt-joule",
    kind: "constant",
    name: "Electron volt (joules)",
    symbol: "1 eV",
    value: "1.60e-19",
    units: "J",
    latex: "1\\,\\text{eV} = 1.60\\times10^{-19}\\,\\text{J}",
    text: "Energy gained by one electron through 1 volt.",
    tags: ["modern", "units"],
    category: "Constants",
    popularity: 6,
    source: "AP Physics 2 constants table",
  },
];

export const seedItems = [...base, ...ap2Extras, ...ap2EarlierAdds];
