import { Item } from "./types";

// Starter items are taken/adapted from:
// - UIUC Physics 101 Formula Sheet (2025)
// - FYKOS "List of constants" (2024)
//
// These are practical PHYS 1–2 level entries. Add more any time via the UI.
export const seedItems: Item[] = [
  // --- Kinematics
  {
    id: "kinematics-1",
    kind: "equation",
    name: "Definition of acceleration",
    latex: "a = \\frac{\\Delta v}{\\Delta t}",
    text: "Average acceleration",
    tags: ["kinematics", "acceleration"],
    category: "Kinematics",
    popularity: 8,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "kinematics-2",
    kind: "equation",
    name: "Uniform acceleration (1)",
    latex: "v = v_0 + a t",
    text: "Velocity update under constant acceleration",
    tags: ["kinematics", "projectile"],
    category: "Kinematics",
    popularity: 10,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "kinematics-3",
    kind: "equation",
    name: "Uniform acceleration (2)",
    latex: "x = x_0 + v_0 t + \\tfrac{1}{2} a t^2",
    text: "Displacement under constant acceleration",
    tags: ["kinematics"],
    category: "Kinematics",
    popularity: 9,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "kinematics-4",
    kind: "equation",
    name: "Uniform acceleration (3)",
    latex: "v^2 = v_0^2 + 2 a \\Delta x",
    text: "Velocity-position relation without time",
    tags: ["kinematics"],
    category: "Kinematics",
    popularity: 9,
    source: "UIUC PHYS 101 formula sheet",
  },
  // --- Dynamics / Energy
  {
    id: "newton-2",
    kind: "equation",
    name: "Newton's 2nd Law",
    latex: "\\sum F = m a",
    text: "Net force equals mass times acceleration",
    tags: ["dynamics", "forces"],
    category: "Dynamics",
    popularity: 10,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "work-energy",
    kind: "equation",
    name: "Work–Kinetic Energy",
    latex: "W = \\Delta K",
    text: "Net work equals change in kinetic energy",
    tags: ["work", "energy"],
    category: "Work & Energy",
    popularity: 8,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "grav-ue",
    kind: "equation",
    name: "Gravitational potential (near Earth)",
    latex: "U = m g h",
    text: "Approximation near Earth's surface",
    tags: ["energy", "gravity"],
    category: "Work & Energy",
    popularity: 7,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "spring-energy",
    kind: "equation",
    name: "Spring potential energy",
    latex: "U_s = \\tfrac{1}{2} k x^2",
    text: "Hooke's law energy",
    tags: ["spring", "energy"],
    category: "Work & Energy",
    popularity: 7,
    source: "UIUC PHYS 101 formula sheet",
  },
  // --- Momentum
  {
    id: "momentum",
    kind: "equation",
    name: "Momentum",
    latex: "p = m v",
    text: "Linear momentum",
    tags: ["momentum"],
    category: "Momentum",
    popularity: 8,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "impulse",
    kind: "equation",
    name: "Impulse–Momentum",
    latex: "J = F \\Delta t = \\Delta p",
    text: "Impulse equals change in momentum",
    tags: ["impulse", "momentum"],
    category: "Momentum",
    popularity: 7,
    source: "UIUC PHYS 101 formula sheet",
  },
  // --- Rotation
  {
    id: "rot-kin-1",
    kind: "equation",
    name: "Angular kinematics (1)",
    latex: "\\omega = \\omega_0 + \\alpha t",
    text: "Constant angular acceleration",
    tags: ["rotation"],
    category: "Rotation",
    popularity: 6,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "rot-energy",
    kind: "equation",
    name: "Rotational kinetic energy",
    latex: "K = \\tfrac{1}{2} I \\omega^2",
    text: "Rotational energy",
    tags: ["rotation", "energy"],
    category: "Rotation",
    popularity: 6,
    source: "UIUC PHYS 101 formula sheet",
  },
  // --- Fluids / Thermo / SHM
  {
    id: "ideal-gas",
    kind: "equation",
    name: "Ideal gas law",
    latex: "P V = n R T",
    text: "Moles form",
    tags: ["thermo", "gas"],
    category: "Thermodynamics",
    popularity: 9,
    source: "UIUC PHYS 101 formula sheet",
  },
  {
    id: "simple-spring",
    kind: "equation",
    name: "SHM: mass–spring angular frequency",
    latex: "\\omega = \\sqrt{\\frac{k}{m}}",
    text: "Simple harmonic motion",
    tags: ["shm", "spring"],
    category: "Oscillations",
    popularity: 7,
    source: "UIUC PHYS 101 formula sheet",
  },
  // --- Constants (FYKOS or common values)
  {
    id: "c",
    kind: "constant",
    name: "Speed of light in vacuum",
    symbol: "c",
    value: "2.998e8",
    units: "m s^-1",
    latex: "c = 2.998 \\times 10^{8} \\, \\text{m}\\,\\text{s}^{-1}",
    text: "Exact by definition",
    tags: ["em", "fundamental"],
    category: "Constants",
    popularity: 10,
    source: "FYKOS constants",
  },
  {
    id: "g",
    kind: "constant",
    name: "Standard gravity (approx.)",
    symbol: "g",
    value: "9.81",
    units: "m s^-2",
    latex: "g \\approx 9.81 \\, \\text{m}\\,\\text{s}^{-2}",
    text: "Near Earth's surface, typical",
    tags: ["gravity"],
    category: "Constants",
    popularity: 10,
    source: "FYKOS constants",
  },
  {
    id: "G",
    kind: "constant",
    name: "Gravitational constant",
    symbol: "G",
    value: "6.674e-11",
    units: "m^3 kg^-1 s^-2",
    latex: "G = 6.674 \\times 10^{-11} \\, \\text{m}^3\\,\\text{kg}^{-1}\\,\\text{s}^{-2}",
    text: "Universal gravitational constant",
    tags: ["gravity"],
    category: "Constants",
    popularity: 8,
    source: "FYKOS constants",
  },
  {
    id: "NA",
    kind: "constant",
    name: "Avogadro constant",
    symbol: "N_A",
    value: "6.022e23",
    units: "mol^-1",
    latex: "N_A = 6.022 \\times 10^{23} \\, \\text{mol}^{-1}",
    text: "Particles per mole (exact by definition in SI)",
    tags: ["thermo"],
    category: "Constants",
    popularity: 8,
    source: "FYKOS constants",
  },
  {
    id: "kB",
    kind: "constant",
    name: "Boltzmann constant",
    symbol: "k_B",
    value: "1.381e-23",
    units: "J K^-1",
    latex: "k_B = 1.381 \\times 10^{-23} \\, \\text{J}\\,\\text{K}^{-1}",
    text: "Relates temperature to energy",
    tags: ["thermo"],
    category: "Constants",
    popularity: 7,
    source: "FYKOS constants",
  },
  {
    id: "R",
    kind: "constant",
    name: "Molar gas constant",
    symbol: "R",
    value: "8.314",
    units: "J mol^-1 K^-1",
    latex: "R = 8.314 \\, \\text{J}\\,\\text{mol}^{-1}\\,\\text{K}^{-1}",
    text: "Ideal gas constant",
    tags: ["thermo"],
    category: "Constants",
    popularity: 7,
    source: "FYKOS constants",
  },
];
